config/routes.rb
Rails31DeviseCancan::Application.routes.draw do

  resources :activities

  resources :activity_types

  resources :result_types

  root :to => "home#index"

  resources :clients do
    collection do
      get 'bring_in'
      get 'suggest'
    end
    member do 
      get 'update_exist'
    end
  end

  resources :import_clients do
    collection do
      get 'search'
    end
  end

  resources :companies

  resources :banners

  devise_for :users
  resources  :users

end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :banner
  has_many :traces
  has_many :companies, :through => :traces
  has_many :activities

  # for pagination with will_paginate
  cattr_reader :per_page
  @@per_page = Rails31DeviseCancan::Application.config.per_page

  def self.exist_by_name? name
    return true unless self.where('name LIKE ?', '%' + name + '%').empty? #self.find_by_name(name.downcase)
    return false
  end

  def self.clients_suggested name
    self.where('name LIKE ?', '%' + name + '%')
  end

end

app/controllers/clients_controller.rb
class ClientsController < InheritedResources::Base
  load_and_authorize_resource
  after_filter :destroy_import_client_session, :only => [:create, :update]
  before_filter :destroy_session_key, :only => [:index, :show]

  def suggest
    import_client = ImportClient.find(params[:import_id])
    name = import_client.name
    session[:import_client] = import_client
    @clients = Client.clients_suggested( name )
  end

  # create a new client from import_client with import_id
  def bring_in
    if session[:import_client]
      ic = session[:import_client]
      @client = Client.new(
                  :name => ic.name,
                  :address => ic.address,
                  :city => ic.city,
                  :postal_code => ic.postal_code,
                  :phone => ic.phone)
    else
      redirect_to import_clients_path 
    end
  end

  def update_exist
    if session[:import_client]
      ic = session[:import_client]
      @client = Client.find(params[:id])  
      @client.name = ic.name
      @client.address = ic.address
      @client.city = ic.city
      @client.postal_code = ic.postal_code
      @client.phone = ic.phone
    else
      redirect_to import_clients_path
    end
  end

  protected 
  def destroy_import_client_session
    if session[:import_client]
      import_client = session[:import_client]
      import_client.update_attribute( :new, false )
      destroy_session_key
    end
  end

  def destroy_session_key 
    session[:import_client] = nil
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.haml
= form_for @client do |f|
  -if @client.errors.any?
    #error_explanation
      %h2= "#{pluralize(@client.errors.count, "error")} prohibited this client from being saved:"
      %ul
        - @client.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :active
    = f.check_box :active
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :address
    = f.text_field :address
  .field
    = f.label :city
    = f.text_field :city
  .field
    = f.label :postal_code
    = f.text_field :postal_code
  .field
    = f.label :phone
    = f.text_field :phone
  .field
    = f.label :banner_id
    = f.number_field :banner_id
  .actions
    = f.submit 'Save'

app/views/clients/bring_in.html.haml
%h1 Import new client

= render 'form'

= link_to 'Back', clients_path

app/views/clients/edit.html.haml
%h1 Editing client

= render 'form'

= link_to 'Show', @client
\|
= link_to 'Back', clients_path

app/views/clients/import.html.haml
%h1 New client

= render 'form'

= link_to 'Back', clients_path

app/views/clients/index.html.haml
%h1 Listing clients

%table
  %tr
    %th Active
    %th Name
    %th Address
    %th City
    %th Postal code
    %th Phone
    %th Banner
    %th
    %th
    %th

  - @clients.each do |client|
    %tr
      %td= client.active
      %td= client.name
      %td= client.address
      %td= client.city
      %td= client.postal_code
      %td= client.phone
      %td= client.banner_id
      %td= link_to 'Show', client
      %td= link_to 'Edit', edit_client_path(client)
      %td= link_to 'Destroy', client, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Client', new_client_path

app/views/clients/new.html.haml
%h1 New client

= render 'form'

= link_to 'Back', clients_path

app/views/clients/show.html.haml
%p#notice= notice

%p
  %b Active:
  = @client.active
%p
  %b Name:
  = @client.name
%p
  %b Address:
  = @client.address
%p
  %b City:
  = @client.city
%p
  %b Postal code:
  = @client.postal_code
%p
  %b Phone:
  = @client.phone
%p
  %b Banner:
  = @client.banner_id

= link_to 'Edit', edit_client_path(@client)
\|
= link_to 'Back', clients_path

app/views/clients/suggest.html.haml
%h1 Suggestion clients

%table
  %tr
    %th Name
    %th Address
    %th City
    %th Postal code
    %th Phone
    %th Banner
    %th
    %th

  - @clients.each do |client|
    %tr
      %td= client.name
      %td= client.address
      %td= client.city
      %td= client.postal_code
      %td= client.phone
      %td= client.banner_id
      %td= @import_id
      %td= link_to 'Update', update_exist_client_path(client)

%br

= link_to 'Create New Client', bring_in_clients_path

app/views/clients/update_exist.html.haml
%h1 Update existing client

= render 'form'

= link_to 'Show', @client
\|
= link_to 'Back', clients_path