config/routes.rb
Rails31DeviseCancan::Application.routes.draw do

  resources :activities

  resources :activity_types

  resources :result_types

  root :to => "home#index"

  resources :clients do
    collection do
      get 'bring_in'
      get 'suggest'
    end
    member do 
      get 'update_exist'
    end
  end

  resources :import_clients do
    collection do
      get 'search'
    end
  end

  resources :companies

  resources :banners

  devise_for :users
  resources  :users

end

app/controllers/activity_types_controller.rb
class ActivityTypesController < InheritedResources::Base
end

app/helpers/activity_types_helper.rb
module ActivityTypesHelper
end

app/views/activity_types/_form.html.haml
= form_for @activity_type do |f|
  -if @activity_type.errors.any?
    #error_explanation
      %h2= "#{pluralize(@activity_type.errors.count, "error")} prohibited this activity_type from being saved:"
      %ul
        - @activity_type.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :active
    = f.check_box :active
  .actions
    = f.submit 'Save'

app/views/activity_types/edit.html.haml
%h1 Editing activity_type

= render 'form'

= link_to 'Show', @activity_type
\|
= link_to 'Back', activity_types_path

app/views/activity_types/index.html.haml
%h1 Listing activity_types

%table
  %tr
    %th Name
    %th Active
    %th
    %th
    %th

  - @activity_types.each do |activity_type|
    %tr
      %td= activity_type.name
      %td= activity_type.active
      %td= link_to 'Show', activity_type
      %td= link_to 'Edit', edit_activity_type_path(activity_type)
      %td= link_to 'Destroy', activity_type, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Activity type', new_activity_type_path

app/views/activity_types/new.html.haml
%h1 New activity_type

= render 'form'

= link_to 'Back', activity_types_path

app/views/activity_types/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @activity_type.name
%p
  %b Active:
  = @activity_type.active

= link_to 'Edit', edit_activity_type_path(@activity_type)
\|
= link_to 'Back', activity_types_path