config/routes.rb
Rails31DeviseCancan::Application.routes.draw do

  resources :activities

  resources :activity_types

  resources :result_types

  root :to => "home#index"

  resources :clients do
    collection do
      get 'bring_in'
      get 'suggest'
    end
    member do 
      get 'update_exist'
    end
  end

  resources :import_clients do
    collection do
      get 'search'
    end
  end

  resources :companies

  resources :banners

  devise_for :users
  resources  :users

end

app/models/import_client.rb
class ImportClient < ActiveRecord::Base

  # for pagination with will_paginate
  cattr_reader :per_page
  @@per_page = Rails31DeviseCancan::Application.config.per_page
  
  # Sunspot / Solr search indexing
  searchable do
    text :name
    text :sort_key
    text :address
    text :city
    text :postal_code
    text :phone
    text :created_at
    time :created_at
    integer :company_id, :references => Company
  end


end

app/controllers/import_clients_controller.rb
class ImportClientsController < InheritedResources::Base
  load_and_authorize_resource
  def index
    search = Sunspot.search(ImportClient) do
      keywords(params[:q])
      paginate(:page => params[:page], :per_page=> Rails31DeviseCancan::Application.config.per_page)
    end
    @import_clients = search.results

    #@import_clients = ImportClient.paginate :page => params[:page], :order => 'created_at DESC'
  end
  def search
    search = Sunspot.search(ImportClient) do
      keywords(params[:q])
    end
    @import_clients = search.results
  end
end

app/helpers/import_clients_helper.rb
module ImportClientsHelper
end

app/views/import_clients/_form.html.haml
= form_for @import_client do |f|
  -if @import_client.errors.any?
    #error_explanation
      %h2= "#{pluralize(@import_client.errors.count, "error")} prohibited this import_client from being saved:"
      %ul
        - @import_client.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :company_id
    = f.number_field :company_id
  .field
    = f.label :client_no
    = f.number_field :client_no
  .field
    = f.label :active
    = f.check_box :active
  .field
    = f.label :sort_key
    = f.text_field :sort_key
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :address
    = f.text_field :address
  .field
    = f.label :city
    = f.text_field :city
  .field
    = f.label :postal_code
    = f.text_field :postal_code
  .field
    = f.label :phone
    = f.text_field :phone
  .field
    = f.label :new
    = f.check_box :new
  .actions
    = f.submit 'Save'

app/views/import_clients/edit.html.haml
%h1 Editing import_client

= render 'form'

= link_to 'Show', @import_client
\|
= link_to 'Back', import_clients_path

app/views/import_clients/index.html.haml
%h1 Listing import_clients
=form_tag import_clients_path, :method => :get do
  = text_field_tag :q, params[:q]
  = submit_tag 'Search'
= page_entries_info @import_clients
%table
  %tr
    %th Company
    %th Client no
    %th Active
    %th Sort key
    %th Name
    %th Adress
    %th City
    %th Postal code
    %th Phone
    %th New
    %th
    /%th
    /%th
    %th

  - @import_clients.each do |import_client|
    %tr
      %td= import_client.company_id
      %td= import_client.client_no
      %td= import_client.active
      %td= import_client.sort_key
      %td= import_client.name
      %td= import_client.address
      %td= import_client.city
      %td= import_client.postal_code
      %td= import_client.phone
      %td= import_client.new
      %td= link_to 'Show', import_client
      %td= link_to_if import_client.new?, 'Import', suggest_clients_path(:import_id => import_client) 

%br

= will_paginate @import_clients

= link_to 'New Import client', new_import_client_path

app/views/import_clients/new.html.haml
%h1 New import_client

= render 'form'

= link_to 'Back', import_clients_path

app/views/import_clients/search.html.haml
%h1 Search result 
=form_tag search_import_clients_path, :method => :get do
  = text_field_tag :q, params[:q]
  = submit_tag 'Search'

%table
  %tr
    %th Company
    %th Client no
    %th Active
    %th Sort key
    %th Name
    %th Adress
    %th City
    %th Postal code
    %th Phone
    %th New
    %th
    /%th
    /%th
    %th

  - @import_clients.each do |import_client|
    %tr
      %td= import_client.company_id
      %td= import_client.client_no
      %td= import_client.active
      %td= import_client.sort_key
      %td= import_client.name
      %td= import_client.address
      %td= import_client.city
      %td= import_client.postal_code
      %td= import_client.phone
      %td= import_client.new
      %td= link_to 'Show', import_client
      /%td= link_to 'Edit', edit_import_client_path(import_client)
      /%td= link_to 'Destroy', import_client, :confirm => 'Are you sure?', :method => :delete
      %td= link_to_if import_client.new?, 'Import', suggest_clients_path(:import_id => import_client) 

app/views/import_clients/show.html.haml
%p#notice= notice

%p
  %b Company:
  = @import_client.company_id
%p
  %b Client no:
  = @import_client.client_no
%p
  %b Active:
  = @import_client.active
%p
  %b Sort key:
  = @import_client.sort_key
%p
  %b Name:
  = @import_client.name
%p
  %b Address:
  = @import_client.address
%p
  %b City:
  = @import_client.city
%p
  %b Postal code:
  = @import_client.postal_code
%p
  %b Phone:
  = @import_client.phone
%p
  %b New:
  = @import_client.new

= link_to 'Edit', edit_import_client_path(@import_client)
\|
= link_to 'Back', import_clients_path