config/routes.rb
Rails31DeviseCancan::Application.routes.draw do

  resources :activities

  resources :activity_types

  resources :result_types

  root :to => "home#index"

  resources :clients do
    collection do
      get 'bring_in'
      get 'suggest'
    end
    member do 
      get 'update_exist'
    end
  end

  resources :import_clients do
    collection do
      get 'search'
    end
  end

  resources :companies

  resources :banners

  devise_for :users
  resources  :users

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :import_clients
  has_many :traces 
  has_many :clients, :through => :traces
end

app/controllers/companies_controller.rb
class CompaniesController < InheritedResources::Base
  load_and_authorize_resource
  respond_to :html, :xml, :json
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.haml
= form_for @company do |f|
  -if @company.errors.any?
    #error_explanation
      %h2= "#{pluralize(@company.errors.count, "error")} prohibited this company from being saved:"
      %ul
        - @company.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/companies/edit.html.haml
%h1 Editing company

= render 'form'

= link_to 'Show', @company
\|
= link_to 'Back', companies_path

app/views/companies/index.html.haml
%h1 Listing companies

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @companies.each do |company|
    %tr
      %td= company.name
      %td= link_to 'Show', company
      %td= link_to 'Edit', edit_company_path(company)
      %td= link_to 'Destroy', company, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Company', new_company_path

app/views/companies/new.html.haml
%h1 New company

= render 'form'

= link_to 'Back', companies_path

app/views/companies/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @company.name

= link_to 'Edit', edit_company_path(@company)
\|
= link_to 'Back', companies_path